# Generated by Django 5.0.7 on 2024-07-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'QORALAMA'), ('SUBMITTED', 'ARIZA YUBORILDI'), ('REJECTED', 'ARIZA RAD ETILDI'), ('ACCEPTED', 'ARIZA QABUL QILINDI'), ('EXAMINED', 'IMTIHON TOPSHIRDI'), ('FAILED', 'IMTIHON MUVAFFAQIYATSIZ'), ('PASSED', "IMTHONDAN MUVAFFAQIYATLI O'TDI")], max_length=25, null=True),
        ),
    ]
